version: "3.8"
services:
  db:
    image: timescale/timescaledb:latest-pg14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nft
      POSTGRES_DB: nft_data
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  app:
    build: .
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app/
