version: "3.8"
services:
  db:
    image: timescale/timescaledb:latest-pg14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nft
      POSTGRES_DB: nft_data
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    # wait for db container finished
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
  app:
    build: ./
    depends_on:
      db:
        # then call index.js
        condition: service_healthy
    volumes:
      - ./:/app/
      - /app/node_modules
